In [1]:
import numpy as np
import numpy.random as rand

In [2]:
a = np.array([1, 3, 9, 16])     
print(type(a))
print(a.shape)
print(" ")

b = np.array([[1, 3, 7], [2, 4, 9]])
print(type(b))
print(b.shape)
print(" ")

<class 'numpy.ndarray'>
(4,)
 
<class 'numpy.ndarray'>
(2, 3)
 


In [3]:
a = np.zeros((2, 2, 5)) #2 страницы, 2 строки на странице, 5 столбцов на странице
print(a)
print(" ")

b = np.eye(7) # единичная матрица 
print(b)
print(" ")

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
 
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
 


In [4]:
a = np.arange(10, 20, 2)
print(a)
print(" ")

[10 12 14 16 18]
 


Если хотим задать сколько знаков после запятой выводить в числах, сколько чисел выводить на экран и др. надо задать опции вывода set_printoptions:
параметр treshold: сколько чисел на экран выводить
параметр precision: сколько знаков после запятой выводить в числах

np.set_printoptions(threshold=10000, precision=2)  будем выводить до 10 десяти тысяч чисел, два знака после запятой.

In [5]:
print(np.random.sample(6))
print(" ")

[0.62204174 0.23761283 0.15504262 0.73916732 0.05322869 0.05090245]
 


In [6]:
a = np.array([[1, 3, 4], [1, 2, 0], [8, 88, 888], [750, 150, 50]])
print(a)
#print(arr1.shape)
print(" ")
print(a[[2,1], 2])
print(" ")

[[  1   3   4]
 [  1   2   0]
 [  8  88 888]
 [750 150  50]]
 
[888   0]
 


In [7]:
a=2
b=10
print(a+(b-a)*np.random.sample()) # одно случайное число из диапазона [a2,b2)
print(" ")

3.267546377557937
 


In [8]:
a = np.array([1, 9, 1, 0, -3, 5])
np.random.shuffle(a) # перемешать массив 
print(a)
print(" ")

[ 5  1  1  0 -3  9]
 


In [9]:
test = np.arange(9).reshape(1, 1, 3, 3).astype(np.float32)
print(test)

[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
