In [1]:
import numpy as np
import numpy.random as rand

In [2]:
a = np.array([1, 3, 9, 16])     
print(type(a))
print(a.shape)
print(" ")

b = np.array([[1, 3, 7], [2, 4, 9]])
print(type(b))
print(b.shape)
print(" ")

<class 'numpy.ndarray'>
(4,)
 
<class 'numpy.ndarray'>
(2, 3)
 


In [3]:
a = np.zeros((2, 2, 5)) #2 страницы, 2 строки на странице, 5 столбцов на странице
print(a)
print(" ")

b = np.eye(7) # единичная матрица 
print(b)
print(" ")

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
 
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
 


In [4]:
!git push

Everything up-to-date


In [5]:
a = np.arange(10, 20, 2)
print(a)
print(" ")

[10 12 14 16 18]
 


Если хотим задать сколько знаков после запятой выводить в числах, сколько чисел выводить на экран и др. надо задать опции вывода set_printoptions:
параметр treshold: сколько чисел на экран выводить
параметр precision: сколько знаков после запятой выводить в числах

np.set_printoptions(threshold=10000, precision=2)  будем выводить до 10 десяти тысяч чисел, два знака после запятой.

In [6]:
print(np.random.sample(6))
print(" ")

[0.80257971 0.32918537 0.72198356 0.19690908 0.15118934 0.88991731]
 


In [16]:
a = np.array([[1, 3, 4], [1, 2, 0], [8, 88, 888], [750, 150, 50]])
print(a[:, 1])
print(a[::-1, 2])


[  3   2  88 150]
[ 50 888   0   4]


In [15]:
a = np.array([[1, 3, 4], [1, 2, 0], [8, 88, 888], [750, 150, 50]])
print(a)
#print(arr1.shape)
print(" ")
print(a[[2,1], 2])
print(" ")
print(a[2][1])
print(" ")
print(a[[0, 2, 3], 0]) 





[[  1   3   4]
 [  1   2   0]
 [  8  88 888]
 [750 150  50]]
 
[888   0]
 
88
 
[  1   8 750]


In [8]:
a=2
b=10
print(a+(b-a)*np.random.sample()) # одно случайное число из диапазона [a2,b2)
print(" ")

4.810033485919039
 


In [9]:
a = np.array([1, 9, 1, 0, -3, 5])
np.random.shuffle(a) # перемешать массив 
print(a)
print(" ")

[ 9  1  5  1 -3  0]
 


In [10]:
test = np.arange(9).reshape(1, 1, 3, 3).astype(np.float32)
print(test)

[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]


In [ ]:
a = np.array([[1, 2], [2, 8], [-7, 0], [1, 4]])
b = np.array([[0, -2], [12, 1], [5, 14], [-10, -4]])

a + b




array([[  0,  -4],
       [ 24,   8],
       [-35,   0],
       [-10, -16]])

In [23]:
a = np.array([[1, 2], [2, 8], [-7, 0], [1, 4]])
b = np.array([[0, -2], [12, 1], [5, 14], [-10, -4]])

a * b

array([[  0,  -4],
       [ 24,   8],
       [-35,   0],
       [-10, -16]])

In [27]:
a = np.array([[1, 2], [2, 8], [-7, 0], [1, 4]])

np.sum(a)



np.int64(11)

In [30]:
a = np.array([[1, 2], [2, 8], [-7, 0], [1, 4]])

a.min()


np.int64(-7)

In [33]:
a = np.array([[1, 2], [2, 8], [-7, 0], [1, 4]])

a.min(axis=1)


array([ 1,  2, -7,  1])

In [39]:
!git status


On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
